name: project-preparation
on: push
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make setup
      - run: make lint
      - run: make test
      - run: make start
